---
version: 2
updates:

  # Update `Go` dependencies.
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels: ["dependencies", "go"]

  # Update `GitHub Action` dependencies.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels: ["dependencies", "github-actions"]

  # Update `Python` dependencies.
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels: ["dependencies", "python"]

